--Servicio WSCreditosGrupales.TraerComite
DELETE FROM BT119_DB.BTI012 WHERE BTICANNOM='BTDIGITAL' AND BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerComite';
INSERT INTO BT119_DB.BTI012
(BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB)
VALUES('BTDIGITAL', 'BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 'S');

DELETE FROM BT119_DB.BTI014 WHERE BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerComite';
INSERT INTO BT119_DB.BTI014
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTIMTDDSC, BTIMTDNSBT, BTIMTDPGMNOM, BTIMTDPGMMTD, BTIMTDSTATUS, BTIMTDFPATH, BTIMTDENBTRA, BTIMTDESPGGX)
VALUES('BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 'Método para traer nombres del comite', ' ', 'rcfse025', 'execute', 'Validado            ', '', 'N', 'S');

DELETE FROM BT119_DB.BTI019 WHERE BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerComite';
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 1, 'Operacion', 'param0', 'I', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 2, 'nombrePresidente', 'param1', 'O', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 3, 'nombreTesorera', 'param2', 'O', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTMOBILE', 'WSCreditosGrupales', '1', 'TraerComite', 4, 'Erroresnegocio', 'param3', 'S', 'Collection', 'SdtsBTErrorNegocio', '', 'S', 'C', '1', 0, '', 'Errornegocio');



--Servicio BTCorresponsales.RegistrarDetallePago
DELETE FROM BT119_DB.BTI012 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='RegistrarDetallePago';
INSERT INTO BT119_DB.BTI012
(BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB)
VALUES('BTINTERNO', 'BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 'S');
INSERT INTO BT119_DB.BTI012
(BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB)
VALUES('BTDIGITAL', 'BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 'S');


DELETE FROM BT119_DB.BTI014 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='RegistrarDetallePago';
INSERT INTO BT119_DB.BTI014
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTIMTDDSC, BTIMTDNSBT, BTIMTDPGMNOM, BTIMTDPGMMTD, BTIMTDSTATUS, BTIMTDFPATH, BTIMTDENBTRA, BTIMTDESPGGX)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 'Registra el detalle de la pendiente grupal', ' ', 'rcfse026', 'execute', 'Validado            ', '', 'N', 'S');

DELETE FROM BT119_DB.BTI019 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='RegistrarDetallePago';
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 1, 'Operacion', 'param0', 'I', 'Int', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 2, 'Fecha', 'param1', 'I', 'Date', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 3, 'ListaDetallePago', 'param2', 'I', 'Collection', 'SdtSDTCFSESDetallePagoPendiente', '', 'S', 'C', '1', 0, '', 'DetallePago');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 4, 'Canal', 'param3', 'I', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 5, 'ReferenciaPago', 'param4', 'I', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'RegistrarDetallePago', 6, 'Erroresnegocio', 'param5', 'S', 'Collection', 'SdtsBTErrorNegocio', '', 'S', 'C', '1', 0, '', 'Errornegocio');

DELETE FROM BT119_DB.BTI025 WHERE BTISDTNOM='SdtSDTCFSESDetallePagoPendiente';
INSERT INTO BT119_DB.BTI025
(BTISDTNOM, BTISDTVERSION, BTISDTDESCRIP, BTISDTNATIVO, BTISDTFECHA, BTISDTNOMINT, BTISDTESTADO, BTISDTTIPO, BTISDTNAMESPACE)
VALUES('SdtSDTCFSESDetallePagoPendiente', '1', '', 'S', '2024-04-17 13:26:00.000', 'SdtSDTCFSESDetallePagoPendiente', 'Desarrollo          ', 3, 'http://uy.com.dlya.bantotal/BTSOA/');

DELETE FROM BT119_DB.BTI026 WHERE BTISDTNOM='SdtSDTCFSESDetallePagoPendiente' ;
INSERT INTO BT119_DB.BTI026
(BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL)
VALUES('SdtSDTCFSESDetallePagoPendiente', '1', 'Monto', 1, '', 'Monto', 'S', 'B', ' ', 'Double', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026
(BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL)
VALUES('SdtSDTCFSESDetallePagoPendiente', '1', 'TipoDocumento', 2, '', 'TipoDocumento', 'S', 'B', ' ', 'Short', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026
(BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL)
VALUES('SdtSDTCFSESDetallePagoPendiente', '1', 'Documento', 3, '', 'Documento', 'S', 'B', ' ', 'String', '', '', ' ', 0, 'N', '');



--Servicio BTCorresponsales.ConsultarDetallePago
DELETE FROM BT119_DB.BTI012 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='ConsultarDetallePago';
INSERT INTO BT119_DB.BTI012
(BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB)
VALUES('BTINTERNO', 'BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', 'S');
INSERT INTO BT119_DB.BTI012
(BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB)
VALUES('BTDIGITAL', 'BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', 'S');

DELETE FROM BT119_DB.BTI014 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='ConsultarDetallePago';
INSERT INTO BT119_DB.BTI014
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTIMTDDSC, BTIMTDNSBT, BTIMTDPGMNOM, BTIMTDPGMMTD, BTIMTDSTATUS, BTIMTDFPATH, BTIMTDENBTRA, BTIMTDESPGGX)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', '', ' ', 'rcfse027', 'execute', 'Validado            ', '', 'N', 'S');

DELETE FROM BT119_DB.BTI019 WHERE BTINOM='BTSERVICES' AND BTISRVNOM='BTCorresponsales' AND BTISRVVER='1' AND BTIMTDNOM='ConsultarDetallePago';
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', 1, 'Operacion', 'param0', 'I', 'Int', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', 2, 'ListaDetallePago', 'param1', 'O', 'Collection', 'SdtSDTCFSESDetallePagoPendiente', '', 'S', 'C', '1', 0, '', 'DetallePago');
INSERT INTO BT119_DB.BTI019
(BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM)
VALUES('BTSERVICES', 'BTCorresponsales', '1', 'ConsultarDetallePago', 3, 'Erroresnegocio', 'param2', 'S', 'Collection', 'SdtsBTErrorNegocio', '', 'S', 'C', '1', 0, '', 'Errornegocio');


--Servicio WSCreditosGrupales.TraerCreditoGrupal
DELETE FROM BT119_DB.BTI012 WHERE BTICANNOM='BTDIGITAL' AND BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerCreditoGrupal';
INSERT INTO BT119_DB.BTI012 (BTICANNOM, BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVHAB) VALUES('BTDIGITAL', 'BTMOBILE', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 'S');

DELETE FROM BT119_DB.BTI014 WHERE BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerCreditoGrupal';
INSERT INTO BT119_DB.BTI014 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTIMTDDSC, BTIMTDNSBT, BTIMTDPGMNOM, BTIMTDPGMMTD, BTIMTDSTATUS, BTIMTDFPATH, BTIMTDENBTRA, BTIMTDESPGGX) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 'Método para traer Creditos Grupales de un cliente', ' ', 'rcfse030', 'execute', 'Validado            ', '', 'N', 'S');

DELETE FROM BT119_DB.BTI019 WHERE BTINOM='BTMOBILE' AND BTISRVNOM='WSCreditosGrupales' AND BTISRVVER='1' AND BTIMTDNOM='TraerCreditoGrupal';
INSERT INTO BT119_DB.BTI019 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 1, 'Pais         ', 'param0', 'I', 'Short', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 2, 'TipoDocumento', 'param1', 'I', 'Short', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 3, 'NroDocumento ', 'param2', 'I', 'String', '', '', 'B', 'B', '', 0, '', '');
INSERT INTO BT119_DB.BTI019 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 4, 'ListaCredGrupales', 'param3', 'S', 'Collection', 'SdtsdtListaCredGrupal', '', 'S', 'C', '1', 0, '', 'ListaCredGrupal');
INSERT INTO BT119_DB.BTI019 (BTINOM, BTISRVNOM, BTISRVVER, BTIMTDNOM, BTISRVPARPOSI, BTISRVPARNOM, BTISRVPARNOMJAVA, BTISRVPARDIR, BTISRVVARTIPO, BTISRVPARITTIPO, BTISRVPARVALOR, BTISRVCATIT, BTISRVCAT, BTISRVSDTVER, BTISRVPARLARGO, BTISRVPARLVAL, BTISRVPARITNOM) VALUES('BTSERVICES', 'WSCreditosGrupales', '1', 'TraerCreditoGrupal', 5, 'Erroresnegocio', 'param4', 'S', 'Collection', 'SdtsBTErrorNegocio', '', 'S', 'C', '1', 0, '', 'Errornegocio');

--Creación SDT HBTI025
DELETE FROM BT119_DB.BTI025 WHERE BTISDTNOM='SdtsdtListaCredGrupal';
INSERT INTO BT119_DB.BTI025 (BTISDTNOM, BTISDTVERSION, BTISDTDESCRIP, BTISDTNATIVO, BTISDTFECHA, BTISDTNOMINT, BTISDTESTADO, BTISDTTIPO, BTISDTNAMESPACE) VALUES('SdtsdtListaCredGrupal', '1', '', 'S', '2024-06-05 16:40:02.000', 'SdtsdtListaCredGrupal', 'Desarrollo          ', 3, 'http://uy.com.dlya.bantotal/BTSOA/');

DELETE FROM BT119_DB.BTI026 WHERE BTISDTNOM='SdtsdtListaCredGrupal';
INSERT INTO BT119_DB.BTI026 (BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL) VALUES('SdtsdtListaCredGrupal', '1', 'vSccta', 1, 'Cuenta Cliente        ', 'vSccta', 'S', 'B', ' ', 'Int', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026 (BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL) VALUES('SdtsdtListaCredGrupal', '1', 'vSctope', 2, 'Tipo Operación        ', 'vSctope', 'S', 'B', ' ', 'Int', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026 (BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL) VALUES('SdtsdtListaCredGrupal', '1', 'nOperacion', 3, 'Operación             ', 'nOperacion', 'S', 'B', ' ', 'Int', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026 (BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL) VALUES('SdtsdtListaCredGrupal', '1', 'cProduc', 4, 'Producto              ', 'cProduc', 'S', 'B', ' ', 'String', '', '', ' ', 0, 'N', '');
INSERT INTO BT119_DB.BTI026 (BTISDTNOM, BTISDTVERSION, BTISDTELEMNOM, BTISDTELEMPOSI, BTISDTELEMDSC, BTISDTELEMNINT, BTISDTELEMOBL, BTISDTELEMCAT, BTISDTELEMCATIT, BTISDTELEMTIPO, BTISDTELEMSDT, BTISDTELEMSDTVE, BTISDTELEMPLANO, BTISDTELEMLARGO, BTISDTELEMENU, BTISDTELEMVAL) VALUES('SdtsdtListaCredGrupal', '1', 'nTipo', 5, 'Tipo Crédito[G=Grupal]', 'nTipo', 'S', 'B', ' ', 'String', '', '', ' ', 0, 'N', '');


